### ISSUE TITLE
django framework

### ISSUE THREAD

**Issue by LOC1207** [LOC1207/getstartedwithpygame#1]
I want to create a website with the help of Django but facing the issue. can anyone help me in resolving this  [`#issue?`](URL: https://github.com/LOC1207/djangofundamentals.git)

**Comment by khdc-me** [comment]
You need help w/ your 'djangofundamentals' repository? If so, you should probably close this issue and open one [in that repository](https://github.com/LOC1207/djangofundamentals/issues).

I'd do so, but not 100% sure if that's what you are intending to do.

If you want help here, then post your question.

If you want help to be tied to djangofundamentals, close this issue and open up (with the specific problem) at the link I provided above.

:) In either case, I'd be happy to help.
